### ISSUE TITLE
`DB::transaction` in migration causes error.

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/test-plugin#100]
When running `php artisan october:migrate` it results in an error:

```
[2021-10-01 05:48:39] local.ERROR: PDOException: There is no active transaction in C:\laragon\www\test\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php:49
Stack trace:
#0 C:\laragon\www\test\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(49): PDO->commit()
#1 C:\laragon\www\test\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(349): Illuminate\Database\Connection->transaction(Object(Closure))
#2 C:\laragon\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#3 C:\laragon\www\test\plugins\october\test\updates\create_test1_tables.php(44): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
```

When removing the `Db::transaction(function() { });` surrounding around each migration, it works fine.

**Comment by daftspunk** [comment]
Thanks!
